"""Generate the site's HTML from the templates and the data in _src/.

Run from anywhere:  python3 _tools/build.py      (stdlib only)

_src/site.toml holds the data (world grid, entries, URLs); _src/*.html the templates.
Template syntax, applied in this order:
  {{> name}}         partial _src/partials/name.html
  {{token}}          per-page value (paths, metadata, cache-busting hashes) or a block rendered
                     from site.toml; tokens may expand to tokens, up to three levels
  {{cur:tab}}        ' aria-current="page"' on the page's own tab, '' elsewhere
  {{v:path}}         short content hash of a file (from the site root), for ?v= cache-busting

Each page starts with a front block:  <!--page\nkey: value\n...\n-->
Keys: path (output path), tab, title, description, msg (default: the newest news' msg),
scripts (space-separated, from the site root), absolute (yes: root-absolute paths, for 404.html,
which GitHub Pages serves at any depth).
"""
import functools
import hashlib
import json
import re
import textwrap
import tomllib
from html import escape, unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "_src"
DATA = tomllib.loads((SRC / "site.toml").read_text())
SITE = DATA["site"]["url"]
ROOMS = DATA["world"]["rooms"]
LINKS = DATA["world"]["links"]
GENERATED = "<!-- Generated by _tools/build.py from _src/. Edit there, then rebuild. -->\n"

LANG_CODES = {"French": "fr", "English": "en", "Portuguese": "pt", "German": "de"}
TOKEN = re.compile(r"\{\{([A-Za-z0-9_:./-]+)\}\}")
MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()
# grid step -> exit direction (rows grow southward)
DIRS = {(0, -1): ("n", "north"), (1, 0): ("e", "east"), (0, 1): ("s", "south"),
        (-1, 0): ("w", "west")}


@functools.cache
def short_hash(rel):
    return hashlib.md5((ROOT / rel).read_bytes()).hexdigest()[:8]


def front(text):
    m = re.match(r"<!--page\n(.*?)\n-->\n", text, re.S)
    if not m:
        raise SystemExit("template without a <!--page ... --> block")
    meta = dict(line.split(": ", 1) for line in m.group(1).splitlines() if line.strip())
    return meta, text[m.end():]


def include(text):
    for _ in range(3):  # partials may include partials
        text = re.sub(r"\{\{> ([a-z_]+)\}\}",
                      lambda m: (SRC / "partials" / f"{m.group(1)}.html").read_text().rstrip("\n"),
                      text)
    return text


def url_of(rel):
    return SITE + (rel[:-len("index.html")] if rel.endswith("index.html") else rel)


def indent(text, n):
    return "\n".join(" " * n + line.strip() if line.strip() else "" for line in text.splitlines())


# ---- dates: "YYYY" or "YYYY-MM" --------------------------------------------------------

def when(d, year=True):
    y, _, m = d.partition("-")
    shown = (f"{MONTHS[int(m) - 1]} {y}" if year else MONTHS[int(m) - 1]) if m else y
    return f'<time datetime="{d}">{shown}</time>'


def span(a, b=None):
    if not b:
        return when(a)
    return f"{when(a, year=a[:4] != b[:4])}&ndash;{when(b)}"


# ---- blocks rendered from site.toml ----------------------------------------------------

def actions(items, n):
    lis = "".join(f'\n{" " * (n + 2)}<li><a href="{a["href"]}">[{a["label"]}]</a></li>' for a in items)
    return f'{" " * n}<ul class="actions">{lis}\n{" " * n}</ul>'


def entries(key):
    """Experience, talks and teaching: the quest-log entry (an experience's `kind` as a tag; its
    arms id, if any, as its anchor: the work done there links to it)."""
    out = []
    for e in DATA[key]:
        head = e.get("org") or e["title"]
        role = e.get("role") or e.get("venue", "")
        if e.get("kind"):
            role = f'<span class="kind">{e["kind"]}</span> {role}'
        role = " &middot; ".join(x for x in (role, e.get("level"), e.get("hours")) if x)  # (a course's level and volume)
        anchor = f' id="at-{e["arms"]}"' if key == "experience" and e.get("arms") else ""
        body = f'\n              <p>\n{indent(e["text"], 16)}\n              </p>' if e.get("text") else ""
        acts = f'\n{actions(e["actions"], 14)}' if e.get("actions") else ""
        if e.get("thumb"):  # (a talk's first slide)
            body += f'\n              <img class="thumb" src="{{{{root}}}}{e["thumb"]}" alt="The first slide" loading="lazy" width="160" height="90">'
        arms = f' data-arms="{e["arms"]}"' if e.get("arms") else ""
        out.append(f"""            <li class="entry"{anchor}{arms}>
              <div class="entry-head">
                <h3>{head}</h3>
                <span class="date">{span(e.get("from") or e["date"], e.get("to"))}</span>
              </div>
              <p class="role-line">{role}</p>{body}{acts}
            </li>""")
    return "\n\n".join(out)


def figure(f):
    """A work's key figure, in its card (lazy: the list stays light)."""
    if not f:
        return ""
    return (f'\n              <figure class="work-fig"><img src="{{{{root}}}}{f["src"]}" width="{f["w"]}" height="{f["h"]}"'
            f' loading="lazy" alt="{escape(f["alt"])}"><figcaption>{f["caption"]}</figcaption></figure>')


def work():
    """Each piece of work once: its card, its outputs; where it was done (`at`) links to that experience."""
    out = []
    at = {e["arms"]: e["org"] for e in DATA["experience"] if e.get("arms")}
    for p in DATA["work"]:
        where = f' &middot; <a class="at" href="#at-{p["at"]}">{at[p["at"]]}</a>' if p.get("at") in at else ""
        out.append(f"""          <article id="{p["id"]}" class="project">
            <span class="illum" data-img="{p["img"].removeprefix("illum-").removesuffix(".png")}">
              <img src="{{{{root}}}}assets/img/{p["img"]}" width="80" height="80"
                   alt="{escape(p["alt"])}">
            </span>
            <div class="project-body">
              <div class="entry-head">
                <h3>{p["title"]}</h3>
                <span class="date">{when(p["date"])}</span>
              </div>
              <p class="role-line">{p["role"]}{where}</p>
              <p>
{indent(p["text"], 16)}
              </p>{figure(p.get("figure"))}{chr(10) + actions(p["actions"], 14) if p.get("actions") else ""}
            </div>
          </article>""")
    return "\n\n".join(out)


def publications():
    out = []
    for p in DATA["publications"]:
        acts = actions(p.get("actions", []), 14)
        if p.get("bib"):
            acts = acts.replace("\n              </ul>", (
                f'\n                <li><a class="copy-bib" href="{{{{root}}}}assets/bib/{p["bib"]}"'
                ' type="application/x-bibtex">[bib]</a></li>\n              </ul>'))
        if p.get("work"):  # (the work it reports, on the index: its card)
            acts = acts.replace("\n              </ul>", f'\n                <li><a href="#{p["work"]}">[the work]</a></li>\n              </ul>')
        out.append(f"""            <li class="pub">
              <p class="pub-title"><a href="{p["href"]}">{p["title"]}</a></p>
              <p class="pub-authors">{p["authors"]}</p>
              <p class="pub-venue">{p["venue"]}</p>
{acts}
            </li>""")
    return "\n".join(out)


def news():
    """The news, newest first; what is under way (`now`) at their head."""
    out = []
    if now := DATA.get("now"):
        y, _, m = now["date"].partition("-")
        out.append(f'            <li class="now"><time datetime="{now["date"]}">Now, {MONTHS[int(m) - 1]} {y}</time>'
                   f' <span>{" ".join(now["text"].split())}</span></li>')
    return "\n".join(out + [f'            <li>{when(n["date"])} <span>{" ".join(n["text"].split())}</span></li>'
                             for n in DATA["news"]])


def tabs():
    return "\n".join(
        f'          <li><a href="{{{{hash}}}}#{t}"{{{{cur:{t}}}}}><span class="k" aria-hidden="true">'
        f'{i}:</span>{t}<span class="hint">{DATA["tab_hints"][t]}</span></a></li>' for i, t in enumerate(DATA["tabs"], 1))


def stats():
    counts = (("Quests", "Quests", "experience", "Positions held"), ("Pubs", "Tomes", "publications", "Publications"),
              ("Talks", "Orations", "talks", "Talks given"))  # (terminal, castle, section, said plainly)
    return "\n".join(f'      <span title="{plain}"><i class="lbl" data-castle="{castle}">{label}</i>:<b>{len(DATA[k])}</b></span>'
                      for label, castle, k, plain in counts if DATA[k])


def exits(room, root):
    """The "Obvious exits" of `room`, from the grid: one per door, clockwise from north."""
    me = ROOMS[room]
    doors = [b if a == room else a for a, b in LINKS if room in (a, b)]
    lis = []
    for step, (d, word) in DIRS.items():
        for o in doors:
            if (ROOMS[o]["c"] - me["c"], ROOMS[o]["r"] - me["r"]) != step:
                continue
            t = ROOMS[o]
            href = root + (t.get("page") or f"#{o}")
            lis.append(f'              <li data-dir="{d}"><span class="dir" aria-hidden="true">{word}</span>'
                       f' <a href="{href}">{t.get("exit", t["label"])}</a></li>')
    return ("          <div class=\"exits\">\n"
            "            <span class=\"exits-label\">Obvious exits:</span>\n"
            "            <ul>\n" + "\n".join(lis) + "\n            </ul>\n          </div>")


def glance():
    """The site in twenty seconds, under the header's statement (the terminal's): now, the latest work
    (and its report, when the newest reference is that work's), how to write."""
    now = [x["about"].split(",")[0].replace("MSc ", "") for x in DATA["education"] if x.get("now")]
    rows = [("Now", f"MSc {' &middot; '.join(now)}")] if now else []
    pub = DATA["publications"][0] if DATA["publications"] else None
    if DATA["work"]:
        w = DATA["work"][0]
        report = ' &middot; <a href="{{hash}}#publications">[report]</a>' if pub and pub.get("work") == w["id"] else ""
        rows.append(("Latest work", f'<a href="{{{{hash}}}}#{w["id"]}">{w["title"]}</a> ({w["date"][:4]}){report}'))
    if pub and not (DATA["work"] and pub.get("work") == DATA["work"][0]["id"]):
        rows.append(("Latest paper", f'<a href="{{{{hash}}}}#publications">{pub["title"]}</a>'))
    rows.append(("Write", f'<a href="mailto:{DATA["site"]["email"]}">{DATA["site"]["email"]}</a>'))
    return ('          <dl class="glance">\n' + "\n".join(f"            <div><dt>{k}</dt><dd>{v}</dd></div>" for k, v in rows)
            + "\n          </dl>")


def timeline():
    """Studies and posts on one axis of years (About): a bar each, packed in as few rows as they allow;
    a post's bar leads to its entry. Academic years run September to June."""
    def years(e):
        if e.get("from"):
            a = [int(x) for x in e["from"].split("-")]
            b = [int(x) for x in (e.get("to") or e["from"]).split("-")]
            return a[0] + (a[1] - 1) / 12, b[0] + b[1] / 12
        ys = [int(y) for y in re.findall(r"\d{4}", e["dates"])]
        return ys[0] + 8 / 12, ys[-1] + 6 / 12
    items = [("study", unescape(re.split(r"[,;]", re.sub("<[^>]+>", "", x["degree"]))[0]), unescape(x["school"]), None, *years(x))
             for x in DATA["education"]]
    items += [("post", unescape(x["org"]), unescape(x.get("role", "")), x.get("arms"), *years(x)) for x in DATA["experience"]]
    y0 = int(min(i[4] for i in items)); y1 = int(max(i[5] for i in items)) + 1
    lanes = {}
    out = []
    for kind, label, sub, arms, a, b in sorted(items, key=lambda i: (i[0] != "study", i[4])):
        rows = lanes.setdefault(kind, [])
        row = next((k for k, end in enumerate(rows) if end <= a), len(rows))
        if row == len(rows):
            rows.append(b)
        else:
            rows[row] = b
        tag = f'a href="#at-{arms}"' if arms else "span"
        out.append(f'              <li class="tl-{kind}" style="--a:{(a - y0) / (y1 - y0):.4f};--b:{(b - y0) / (y1 - y0):.4f};--row:{row}">'
                   f'<{tag} title="{escape(sub)}">{escape(label)}</{tag.split()[0]}></li>')
    ticks = "".join(f'<li style="--a:{(y - y0) / (y1 - y0):.4f}">{y}</li>' for y in range(y0, y1 + 1))
    return (f'          <figure class="timeline" style="--study:{len(lanes.get("study", []))};--post:{len(lanes.get("post", []))}" aria-label="Studies and positions, by year">\n'
            f'            <ol class="tl-bars">\n' + "\n".join(out) + f'\n            </ol>\n            <ol class="tl-years" aria-hidden="true">{ticks}</ol>\n          </figure>')


def jsonld():
    s, p = DATA["site"], DATA["person"]
    college = lambda name: {"@type": "CollegeOrUniversity", "name": name}  # noqa: E731
    doc = {
        "@context": "https://schema.org",
        "@type": "Person",
        "name": s["name"],
        "url": SITE,
        "image": SITE + "assets/img/og.png",
        "email": f"mailto:{s['email']}",
        "jobTitle": s["role"],
        "homeLocation": {"@type": "Place", "name": f"{s['place']}, France"},
        "affiliation": [college(x["school"]) for x in DATA["education"] if x.get("now")],
        "alumniOf": [college(x) for x in p["alumni_of"]],
        "knowsAbout": p["knows_about"],
        "knowsLanguage": [LANG_CODES[name] for name, _ in p["languages"] if name in LANG_CODES],
        "sameAs": [s["github"], s["linkedin"]],
    }
    return textwrap.indent(json.dumps(doc, ensure_ascii=False, indent=2), "  ")


def site_json():
    """What script.js and dungeon.js need: the world, and where the objects lead."""
    bib = next((p["bib"] for p in DATA["publications"] if p.get("bib")), None)
    doc = {"world": ROOMS, "links": LINKS, "email": DATA["site"]["email"],
           "github": DATA["site"]["github"], "bib": bib and f"assets/bib/{bib}",
           "heraldry": DATA["heraldry"], "library": DATA.get("library", {})}
    return json.dumps(doc, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def site_tokens(text):
    """Expand the data tokens of site.toml outside a page (the feed): links become absolute."""
    s = DATA["site"]
    plain = {"root": SITE, "email": s["email"], "github": s["github"]}
    return TOKEN.sub(lambda m: DATA["urls"][m.group(1)[4:]] if m.group(1).startswith("url:")
                     else plain[m.group(1)], text)


def feed():
    """Atom feed of the news; entry ids count from the oldest, so they never change."""
    s = DATA["site"]
    absolute = lambda html: re.sub(r'href="(?!https?:|mailto:|#)', f'href="{SITE}', html)  # noqa: E731
    stamp = lambda d: f"{d}-01T00:00:00Z" if len(d) == 7 else f"{d}-01-01T00:00:00Z"  # noqa: E731
    n = len(DATA["news"])
    items = []
    for i, e in enumerate(DATA["news"]):
        text = site_tokens(" ".join(e["text"].split()))
        title = re.split(r"(?<=\.)\s", re.sub(r"<[^>]+>", "", text), maxsplit=1)[0]
        items.append(f"""  <entry>
    <title>{escape(title)}</title>
    <link href="{SITE}#news"/>
    <id>{SITE}#news-{n - i}</id>
    <updated>{stamp(e["date"])}</updated>
    <content type="html">{escape(absolute(text))}</content>
  </entry>""")
    return f"""<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>{escape(s["name"])}: news</title>
  <link href="{SITE}"/>
  <link rel="self" href="{SITE}feed.xml"/>
  <id>{SITE}</id>
  <updated>{stamp(DATA["news"][0]["date"])}</updated>
  <author><name>{escape(s["name"])}</name></author>
{chr(10).join(items)}
</feed>
"""


def coursework():
    """The book of courses: every course followed, grouped by year, then by school (no grades)."""
    years = {}
    for e in DATA.get("coursework", []):
        years.setdefault(e["years"], []).append(e)
    n = sum(len(e["courses"]) for e in DATA.get("coursework", []))
    out = []
    for y, progs in years.items():
        body = "".join(f"""
                <p class="ledger-prog">{e["school"]} &middot; {e["programme"]}</p>
                <ul class="flow">{" ".join(f"<li>{c}</li>" for c in e["courses"])}</ul>""" for e in progs)
        out.append(f"""              <section class="ledger-year">
                <h3>{y}</h3>{body}
              </section>""")
    return (f"""          <details class="ledger" id="coursework">
            <summary>The book of courses <span class="meta">({n} courses)</span></summary>
""" + "\n".join(out) + "\n          </details>")


BLOCKS = {
    "list:experience": lambda: entries("experience"),
    "list:talks": lambda: entries("talks"),
    "list:teaching": lambda: entries("teaching"),
    "list:work": work,
    "list:publications": publications,
    "list:news": news,
    "tabs": tabs,
    "stats": stats,
    "jsonld": jsonld,
    "studying": lambda: "\n".join(f"              <span data-arms=\"{x['arms']}\">{x['about']}</span>"
                                  for x in DATA["education"] if x.get("now")),
    "languages": lambda: " &middot; ".join(f"{n}&nbsp;<span class=\"meta\">({lvl})</span>" for n, lvl in DATA["person"]["languages"]),
    "coursework": coursework,
    "glance": glance,
    "timeline": timeline,
    "drawn_to": lambda: "\n".join(f"                <li>{x}</li>" for x in DATA["person"]["drawn_to"]),
}


def render(src):
    meta, body = front(src.read_text())
    rel = meta["path"]
    depth = rel.count("/")
    root = "/" if meta.get("absolute") == "yes" else "../" * depth
    home = root or "./"
    # Section links on the index must stay bare "#id" (windowed panes).
    is_index = rel == "index.html"
    page_js = meta.get("scripts", "").split()
    scripts = "".join(f'\n  <script src="{root}{s}?v={short_hash(s)}" defer></script>'
                      for s in page_js)
    s = DATA["site"]
    values = {
        "root": root,
        "home": home,
        "hash": "" if is_index else home,
        "title": meta["title"],
        "description": meta["description"],
        "msg": meta.get("msg") or DATA["news"][0]["msg"],
        "canonical": url_of(rel),
        "scripts": scripts,
        "og_image": SITE + "assets/img/og.png",
        "name_tag": "h1" if is_index else "p",
        "name": s["name"], "role": s["role"], "place": s["place"],
        "email": s["email"], "github": s["github"],
        "github_host": s["github"].split("://", 1)[1],
        "n_rooms": str(len(ROOMS)),
        "n_tabs": str(len(DATA["tabs"])),
    }

    def token(m):
        key = m.group(1)
        if key.startswith("v:"):
            return short_hash(key[2:])
        if key.startswith("cur:"):
            return ' aria-current="page"' if key[4:] == meta.get("tab") else ""
        if key.startswith("url:"):
            return DATA["urls"][key[4:]]
        if key.startswith("hidden_if_any:"):  # the empty-section line
            return " hidden" if DATA[key[14:]] else ""
        if key.startswith("exits:"):
            return exits(key[6:], root)
        if key == "site_json":
            return "\0site_json\0"  # JSON may hold "}}": put in after the check below
        if key in BLOCKS:
            return BLOCKS[key]()
        if key not in values:
            raise SystemExit(f"{src.name}: unknown token {{{{{key}}}}}")
        return values[key]

    text = include(body)
    for _ in range(3):
        text = TOKEN.sub(token, text)
    if re.search(r"\{\{|\}\}", text):
        raise SystemExit(f"{src.name}: unprocessed template syntax: {re.findall(r'.{30}(?:\{\{|\}\}).{30}', text)[:3]}")
    text = text.replace("\0site_json\0", site_json())
    text = text.replace("<!doctype html>\n", "<!doctype html>\n" + GENERATED, 1)
    return rel, text, meta


def main():
    pages = sorted(p for p in SRC.rglob("*.html") if "partials" not in p.parts)
    sitemap = []
    for src in pages:
        rel, text, meta = render(src)
        dest = ROOT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text)
        print(f"  {rel}")
        if meta.get("absolute") != "yes":
            sitemap.append(url_of(rel))
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "".join(f"  <url><loc>{u}</loc></url>\n" for u in sitemap)
        + "</urlset>\n")
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {SITE}sitemap.xml\n")
    (ROOT / "feed.xml").write_text(feed())
    print(f"built {len(sitemap) + 1} pages, sitemap.xml, robots.txt, feed.xml")


if __name__ == "__main__":
    main()
