"""Generate the site's HTML from the templates in _src/.

Run from anywhere:  python3 _tools/build.py      (stdlib only)

Template syntax, applied in this order:
  {{> name}}         partial _src/partials/name.html
  {{token}}          per-page value (paths, metadata, cache-busting hashes)
  {{cur:tab}}        ' aria-current="page"' on the page's own tab, '' elsewhere

Each page starts with a front block:  <!--page\nkey: value\n...\n-->
Keys: path (output path), tab, title, description, msg, scripts (space-separated, from the
site root), absolute (yes: root-absolute paths, for 404.html, which GitHub Pages serves at any
depth).
"""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "_src"
SITE = "https://mksv-pro.github.io/"
GENERATED = "<!-- Generated by _tools/build.py from _src/. Edit there, then rebuild. -->\n"

TOKEN = re.compile(r"\{\{([a-z_:]+)\}\}")


def short_hash(rel):
    return hashlib.md5((ROOT / rel).read_bytes()).hexdigest()[:8]


def front(text):
    m = re.match(r"<!--page\n(.*?)\n-->\n", text, re.S)
    if not m:
        raise SystemExit("template without a <!--page ... --> block")
    meta = dict(line.split(": ", 1) for line in m.group(1).splitlines() if line.strip())
    return meta, text[m.end():]


def include(text):
    for _ in range(3):  # partials may include partials
        text = re.sub(r"\{\{> ([a-z_]+)\}\}",
                      lambda m: (SRC / "partials" / f"{m.group(1)}.html").read_text().rstrip("\n"),
                      text)
    return text


def url_of(rel):
    return SITE + (rel[:-len("index.html")] if rel.endswith("index.html") else rel)


def render(src, hashes):
    meta, body = front(src.read_text())
    rel = meta["path"]
    depth = rel.count("/")
    root = "/" if meta.get("absolute") == "yes" else "../" * depth
    home = root or "./"
    # Section links on the index must stay bare "#id" (windowed panes).
    is_index = rel == "index.html"
    scripts = "".join(f'\n  <script src="{root}{s}?v={hashes[s]}" defer></script>'
                      for s in meta.get("scripts", "").split())
    values = {
        "root": root,
        "home": home,
        "hash": "" if is_index else home,
        "title": meta["title"],
        "description": meta["description"],
        "msg": meta.get("msg", ""),
        "canonical": url_of(rel),
        "scripts": scripts,
        "og_image": SITE + "assets/img/og.png",
        "v_css": hashes["styles.css"],
        "v_js": hashes["script.js"],
        "v_cv": hashes["assets/Mike_Silva_CV.pdf"],
        "v_dungeon": hashes["assets/js/dungeon.js"],
        "name_tag": "h1" if is_index else "p",
    }

    def token(m):
        key = m.group(1)
        if key.startswith("cur:"):
            return ' aria-current="page"' if key[4:] == meta.get("tab") else ""
        if key not in values:
            raise SystemExit(f"{src.name}: unknown token {{{{{key}}}}}")
        return values[key]

    text = TOKEN.sub(token, include(body))
    if re.search(r"\{\{|\}\}", text):
        raise SystemExit(f"{src.name}: unprocessed template syntax")
    text = text.replace("<!doctype html>\n", "<!doctype html>\n" + GENERATED, 1)
    return rel, text, meta


def main():
    hashes = {p: short_hash(p) for p in
              ("styles.css", "script.js", "assets/Mike_Silva_CV.pdf",
               "assets/js/dla.js", "assets/js/nbody.js", "assets/js/dungeon.js")}
    pages = sorted(p for p in SRC.rglob("*.html") if "partials" not in p.parts)
    sitemap = []
    for src in pages:
        rel, text, meta = render(src, hashes)
        dest = ROOT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text)
        print(f"  {rel}")
        if meta.get("absolute") != "yes":
            sitemap.append(url_of(rel))
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "".join(f"  <url><loc>{u}</loc></url>\n" for u in sitemap)
        + "</urlset>\n")
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {SITE}sitemap.xml\n")
    print(f"built {len(sitemap) + 1} pages, sitemap.xml, robots.txt")


if __name__ == "__main__":
    main()
