"""Generate the site's HTML from the templates and the data in _src/.

Run from anywhere:  python3 _tools/build.py      (stdlib only)

_src/site.toml holds the data (world grid, entries, URLs); _src/*.html the templates.
Template syntax, applied in this order:
  {{> name}}         partial _src/partials/name.html
  {{token}}          per-page value (paths, metadata, cache-busting hashes) or a block rendered
                     from site.toml; tokens may expand to tokens, up to three levels
  {{cur:tab}}        ' aria-current="page"' on the page's own tab, '' elsewhere
  {{v:path}}         short content hash of a file (from the site root), for ?v= cache-busting

Each page starts with a front block:  <!--page\nkey: value\n...\n-->
Keys: path (output path), tab, title, description, msg (default: the newest news' msg),
scripts (space-separated, from the site root), absolute (yes: root-absolute paths, for 404.html,
which GitHub Pages serves at any depth).
"""
import functools
import hashlib
import json
import re
import textwrap
import tomllib
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "_src"
DATA = tomllib.loads((SRC / "site.toml").read_text())
SITE = DATA["site"]["url"]
ROOMS = DATA["world"]["rooms"]
LINKS = DATA["world"]["links"]
GENERATED = "<!-- Generated by _tools/build.py from _src/. Edit there, then rebuild. -->\n"

TOKEN = re.compile(r"\{\{([A-Za-z0-9_:./-]+)\}\}")
MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()
# grid step -> exit direction (rows grow southward)
DIRS = {(0, -1): ("n", "north"), (1, 0): ("e", "east"), (0, 1): ("s", "south"),
        (-1, 0): ("w", "west")}


@functools.cache
def short_hash(rel):
    return hashlib.md5((ROOT / rel).read_bytes()).hexdigest()[:8]


def front(text):
    m = re.match(r"<!--page\n(.*?)\n-->\n", text, re.S)
    if not m:
        raise SystemExit("template without a <!--page ... --> block")
    meta = dict(line.split(": ", 1) for line in m.group(1).splitlines() if line.strip())
    return meta, text[m.end():]


def include(text):
    for _ in range(3):  # partials may include partials
        text = re.sub(r"\{\{> ([a-z_]+)\}\}",
                      lambda m: (SRC / "partials" / f"{m.group(1)}.html").read_text().rstrip("\n"),
                      text)
    return text


def url_of(rel):
    return SITE + (rel[:-len("index.html")] if rel.endswith("index.html") else rel)


def indent(text, n):
    return "\n".join(" " * n + line.strip() if line.strip() else "" for line in text.splitlines())


# ---- dates: "YYYY" or "YYYY-MM" --------------------------------------------------------

def when(d, year=True):
    y, _, m = d.partition("-")
    shown = (f"{MONTHS[int(m) - 1]} {y}" if year else MONTHS[int(m) - 1]) if m else y
    return f'<time datetime="{d}">{shown}</time>'


def span(a, b=None):
    if not b:
        return when(a)
    return f"{when(a, year=a[:4] != b[:4])}&ndash;{when(b)}"


# ---- blocks rendered from site.toml ----------------------------------------------------

def actions(items, n):
    lis = "".join(f'\n{" " * (n + 2)}<li><a href="{a["href"]}">[{a["label"]}]</a></li>' for a in items)
    return f'{" " * n}<ul class="actions">{lis}\n{" " * n}</ul>'


def entries(key):
    """Research, talks and teaching: the quest-log entry."""
    out = []
    for e in DATA[key]:
        head = e.get("org") or e["title"]
        role = e.get("role") or e.get("venue", "")
        body = f'\n              <p>\n{indent(e["text"], 16)}\n              </p>' if e.get("text") else ""
        acts = f'\n{actions(e["actions"], 14)}' if e.get("actions") else ""
        arms = f' data-arms="{e["arms"]}"' if e.get("arms") else ""
        out.append(f"""            <li class="entry"{arms}>
              <div class="entry-head">
                <h3>{head}</h3>
                <span class="date">{span(e.get("from") or e["date"], e.get("to"))}</span>
              </div>
              <p class="role-line">{role}</p>{body}{acts}
            </li>""")
    return "\n\n".join(out)


def projects():
    out = []
    for p in DATA["projects"]:
        room = ROOMS[p["id"]]
        out.append(f"""          <article id="{p["id"]}" class="project">
            <a class="illum" href="{room["page"]}">
              <img src="{{{{root}}}}assets/img/{room["img"]}" width="80" height="80"
                   alt="{escape(p["alt"])}">
            </a>
            <div class="project-body">
              <div class="entry-head">
                <h3><a href="{room["page"]}">{p["title"]}</a></h3>
                <span class="date">{when(p["date"])}</span>
              </div>
              <p class="role-line">{p["role"]}</p>
              <p>
{indent(p["text"], 16)}
              </p>
{actions(p["actions"], 14)}
            </div>
          </article>""")
    return "\n\n".join(out)


def publications():
    out = []
    for p in DATA["publications"]:
        acts = actions(p.get("actions", []), 14)
        if p.get("bib"):
            acts = acts.replace("\n              </ul>", (
                f'\n                <li><a class="copy-bib" href="{{{{root}}}}assets/bib/{p["bib"]}"'
                ' type="application/x-bibtex">[bib]</a></li>\n              </ul>'))
        out.append(f"""            <li class="pub">
              <p class="pub-title"><a href="{p["href"]}">{p["title"]}</a></p>
              <p class="pub-authors">{p["authors"]}</p>
              <p class="pub-venue">{p["venue"]}</p>
{acts}
            </li>""")
    return "\n".join(out)


def news():
    return "\n".join(f'            <li>{when(n["date"])} <span>{" ".join(n["text"].split())}</span></li>'
                     for n in DATA["news"])


def tabs():
    return "\n".join(
        f'          <li><a href="{{{{hash}}}}#{t}"{{{{cur:{t}}}}}><span class="k" aria-hidden="true">'
        f"{i}:</span>{t}</a></li>" for i, t in enumerate(DATA["tabs"], 1))


def stats():
    counts = (("Quests", "research"), ("Pubs", "publications"), ("Talks", "talks"))
    return "\n".join(f"      <span>{label}:<b>{len(DATA[k])}</b></span>"
                     for label, k in counts if DATA[k])


def exits(room, root):
    """The "Obvious exits" of `room`, from the grid: one per door, clockwise from north."""
    me = ROOMS[room]
    doors = [b if a == room else a for a, b in LINKS if room in (a, b)]
    lis = []
    for step, (d, word) in DIRS.items():
        for o in doors:
            if (ROOMS[o]["c"] - me["c"], ROOMS[o]["r"] - me["r"]) != step:
                continue
            t = ROOMS[o]
            href = root + (t.get("page") or f"#{o}")
            lis.append(f'              <li data-dir="{d}"><span class="dir" aria-hidden="true">{word}</span>'
                       f' <a href="{href}">{t.get("exit", t["label"])}</a></li>')
    return ("          <div class=\"exits\">\n"
            "            <span class=\"exits-label\">Obvious exits:</span>\n"
            "            <ul>\n" + "\n".join(lis) + "\n            </ul>\n          </div>")


def jsonld():
    s, p = DATA["site"], DATA["person"]
    college = lambda name: {"@type": "CollegeOrUniversity", "name": name}  # noqa: E731
    doc = {
        "@context": "https://schema.org",
        "@type": "Person",
        "name": s["name"],
        "url": SITE,
        "image": SITE + "assets/img/og.png",
        "email": f"mailto:{s['email']}",
        "jobTitle": s["role"],
        "homeLocation": {"@type": "Place", "name": f"{s['place']}, France"},
        "affiliation": [college(x["school"]) for x in p["studying"]],
        "alumniOf": [college(x) for x in p["alumni_of"]],
        "knowsAbout": p["knows_about"],
        "knowsLanguage": ["en", "fr"],
        "sameAs": [s["github"]],
    }
    return textwrap.indent(json.dumps(doc, ensure_ascii=False, indent=2), "  ")


def site_json():
    """What script.js and dungeon.js need: the world, and where the objects lead."""
    bib = next((p["bib"] for p in DATA["publications"] if p.get("bib")), None)
    doc = {"world": ROOMS, "links": LINKS, "email": DATA["site"]["email"],
           "github": DATA["site"]["github"], "bib": bib and f"assets/bib/{bib}",
           "heraldry": DATA["heraldry"]}
    return json.dumps(doc, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def site_tokens(text):
    """Expand the data tokens of site.toml outside a page (the feed): links become absolute."""
    s = DATA["site"]
    plain = {"root": SITE, "email": s["email"], "github": s["github"]}
    return TOKEN.sub(lambda m: DATA["urls"][m.group(1)[4:]] if m.group(1).startswith("url:")
                     else plain[m.group(1)], text)


def feed():
    """Atom feed of the news; entry ids count from the oldest, so they never change."""
    s = DATA["site"]
    absolute = lambda html: re.sub(r'href="(?!https?:|mailto:|#)', f'href="{SITE}', html)  # noqa: E731
    stamp = lambda d: f"{d}-01T00:00:00Z" if len(d) == 7 else f"{d}-01-01T00:00:00Z"  # noqa: E731
    n = len(DATA["news"])
    items = []
    for i, e in enumerate(DATA["news"]):
        text = site_tokens(" ".join(e["text"].split()))
        title = re.split(r"(?<=\.)\s", re.sub(r"<[^>]+>", "", text), maxsplit=1)[0]
        items.append(f"""  <entry>
    <title>{escape(title)}</title>
    <link href="{SITE}#news"/>
    <id>{SITE}#news-{n - i}</id>
    <updated>{stamp(e["date"])}</updated>
    <content type="html">{escape(absolute(text))}</content>
  </entry>""")
    return f"""<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>{escape(s["name"])}: news</title>
  <link href="{SITE}"/>
  <link rel="self" href="{SITE}feed.xml"/>
  <id>{SITE}</id>
  <updated>{stamp(DATA["news"][0]["date"])}</updated>
  <author><name>{escape(s["name"])}</name></author>
{chr(10).join(items)}
</feed>
"""


BLOCKS = {
    "list:research": lambda: entries("research"),
    "list:talks": lambda: entries("talks"),
    "list:teaching": lambda: entries("teaching"),
    "list:projects": projects,
    "list:publications": publications,
    "list:news": news,
    "tabs": tabs,
    "stats": stats,
    "jsonld": jsonld,
    "studying": lambda: "\n".join(f"              <span data-arms=\"{x['arms']}\">{x['degree']}</span>"
                                  for x in DATA["person"]["studying"]),
    "drawn_to": lambda: "\n".join(f"                <li>{x}</li>" for x in DATA["person"]["drawn_to"]),
}


def render(src):
    meta, body = front(src.read_text())
    rel = meta["path"]
    depth = rel.count("/")
    root = "/" if meta.get("absolute") == "yes" else "../" * depth
    home = root or "./"
    # Section links on the index must stay bare "#id" (windowed panes).
    is_index = rel == "index.html"
    # demo.js draws the demos the page's own scripts set up
    page_js = meta.get("scripts", "").split()
    page_js = (["assets/js/demo.js"] if page_js else []) + page_js
    scripts = "".join(f'\n  <script src="{root}{s}?v={short_hash(s)}" defer></script>'
                      for s in page_js)
    s = DATA["site"]
    values = {
        "root": root,
        "home": home,
        "hash": "" if is_index else home,
        "title": meta["title"],
        "description": meta["description"],
        "msg": meta.get("msg") or DATA["news"][0]["msg"],
        "canonical": url_of(rel),
        "scripts": scripts,
        "og_image": SITE + "assets/img/og.png",
        "name_tag": "h1" if is_index else "p",
        "name": s["name"], "role": s["role"], "place": s["place"],
        "email": s["email"], "github": s["github"],
        "github_host": s["github"].split("://", 1)[1],
        "n_rooms": str(len(ROOMS)),
    }

    def token(m):
        key = m.group(1)
        if key.startswith("v:"):
            return short_hash(key[2:])
        if key.startswith("cur:"):
            return ' aria-current="page"' if key[4:] == meta.get("tab") else ""
        if key.startswith("url:"):
            return DATA["urls"][key[4:]]
        if key.startswith("hidden_if_any:"):  # the empty-section line
            return " hidden" if DATA[key[14:]] else ""
        if key.startswith("exits:"):
            return exits(key[6:], root)
        if key == "site_json":
            return "\0site_json\0"  # JSON may hold "}}": put in after the check below
        if key in BLOCKS:
            return BLOCKS[key]()
        if key not in values:
            raise SystemExit(f"{src.name}: unknown token {{{{{key}}}}}")
        return values[key]

    text = include(body)
    for _ in range(3):
        text = TOKEN.sub(token, text)
    if re.search(r"\{\{|\}\}", text):
        raise SystemExit(f"{src.name}: unprocessed template syntax: {re.findall(r'.{30}(?:\{\{|\}\}).{30}', text)[:3]}")
    text = text.replace("\0site_json\0", site_json())
    text = text.replace("<!doctype html>\n", "<!doctype html>\n" + GENERATED, 1)
    return rel, text, meta


def main():
    pages = sorted(p for p in SRC.rglob("*.html") if "partials" not in p.parts)
    sitemap = []
    for src in pages:
        rel, text, meta = render(src)
        dest = ROOT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text)
        print(f"  {rel}")
        if meta.get("absolute") != "yes":
            sitemap.append(url_of(rel))
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "".join(f"  <url><loc>{u}</loc></url>\n" for u in sitemap)
        + "</urlset>\n")
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {SITE}sitemap.xml\n")
    (ROOT / "feed.xml").write_text(feed())
    print(f"built {len(sitemap) + 1} pages, sitemap.xml, robots.txt, feed.xml")


if __name__ == "__main__":
    main()
