"""The CV, from the site's own data: _src/site.toml -> _cv/cv.tex -> assets/Mike_Silva_CV.pdf.

  python3 _tools/cv.py            write _cv/cv.tex, build it with latexmk, copy the PDF into assets/
  python3 _tools/cv.py --tex      only write _cv/cv.tex

One source for every fact (site.toml): education, research (cv_* fields), projects (those with a
cv_title), skills and languages ([cv], [person]). Text fields are HTML, as for the site; they are
turned into LaTeX here (<i>, <b>, <sup>, <a>, &amp;, &nbsp;, ×, −). Then run build.py, which
stamps the new PDF's hash on the CV link.
"""
import argparse
import html
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = tomllib.loads((ROOT / "_src" / "site.toml").read_text())
OUT = ROOT / "_cv"
PDF = ROOT / "assets" / "Mike_Silva_CV.pdf"
MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()
SPECIAL = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
           "~": r"\textasciitilde{}", "^": r"\textasciicircum{}", "\\": r"\textbackslash{}"}


def tokens(text):
    """Resolve the site's {{url:key}} tokens."""
    return re.sub(r"\{\{url:([a-z_]+)\}\}", lambda m: DATA["urls"][m.group(1)], text)


def tex(text):
    """HTML (as written in site.toml) to LaTeX: tags become commands, the rest is escaped."""
    out = []
    for part in re.split(r"(<[^>]+>)", tokens(text)):
        if part.startswith("<"):
            tag = part.lower()
            if m := re.match(r'<a href="([^"]+)">', part):
                out.append(r"\href{" + m.group(1).replace("%", r"\%").replace("#", r"\#") + "}{")
            elif tag in ("<i>", "<em>"):
                out.append(r"\textit{")
            elif tag in ("<b>", "<strong>"):
                out.append(r"\textbf{")
            elif tag == "<sup>":
                out.append(r"\textsuperscript{")
            elif tag in ("</a>", "</i>", "</em>", "</b>", "</strong>", "</sup>"):
                out.append("}")
            continue
        s = html.unescape(part.replace("&nbsp;", "\0"))
        s = "".join(SPECIAL.get(c, c) for c in s).replace("\0", "~")
        s = re.sub(r"(?<=\d)\s*×\s*(?=\d)", r"\\,\\texttimes\\,", s)  # 5 × 10: thin spaces
        s = s.replace("×", r"\texttimes{}").replace("−", r"\textminus{}").replace("\u2009", r"\,")
        out.append(s)
    return "".join(out)


def dates(text):
    """Year ranges as the CV sets them: 2026 -- 2027."""
    return re.sub(r"(\d)\s*–\s*(\d)", r"\1 -- \2", tex(text))


def month(ym):
    y, m = ym.split("-")
    return f"{MONTHS[int(m) - 1]} {y}"


def span(e):
    a = month(e["from"]) if "from" in e else month(e["date"]) if "-" in e["date"] else e["date"]
    return f"{a} -- {month(e['to'])}" if e.get("to") else a


PREAMBLE = r"""\documentclass[a4paper,10pt]{article}
%% Generated by _tools/cv.py from _src/site.toml. Edit the data there, then rerun.
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{fontawesome5}
\usepackage{microtype}
\usepackage{textcomp}
\usepackage{geometry}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage{xcolor}
\usepackage{hyperref}

% Real Unicode text layer, so applicant-tracking systems and copy-paste read
% ligatures and accents correctly.
\input{glyphtounicode}
\pdfgentounicode=1

% Black text; navy for headings and links only.
\definecolor{ink}{HTML}{000000}
\definecolor{accent}{RGB}{50,50,100}
\definecolor{muted}{HTML}{555555}

\geometry{top=0.34in, bottom=0.32in, left=0.6in, right=0.6in}

\color{ink}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{1pt}

\titleformat{\section}{\normalfont\large\bfseries\color{accent}}{}{0em}{}[{\color{muted}\titlerule[0.4pt]}]
\titlespacing*{\section}{0pt}{5pt}{3pt}

\setlist[itemize]{noitemsep, topsep=1pt, leftmargin=1.2em, label=\textbullet}

\hypersetup{
  colorlinks=true, linkcolor=accent, urlcolor=accent,
  pdftitle={@NAME@ -- Curriculum Vitae},
  pdfauthor={@NAME@},
  pdfkeywords={@KEYWORDS@}
}

% \entry{Institution}{City, Country}{Title / degree}{Dates}
\newcommand{\entry}[4]{%
  \textbf{#1}\hfill #4\\
  \textit{#3}\hfill {\color{muted}#2}\par}
\newcommand{\coursework}[1]{{\small\color{muted}Coursework: #1}\par\vspace{2pt}}
\newcommand{\skill}[2]{\hangindent=9.5em\hangafter=1\makebox[9.5em][l]{\textbf{#1}}#2\par}

\begin{document}
"""


def header():
    s = DATA["site"]
    host = s["url"].split("://", 1)[1].rstrip("/")
    gh = s["github"].rstrip("/").rsplit("/", 1)[1]
    li = s["linkedin"].rstrip("/").rsplit("/", 1)[1]
    return rf"""
% ---- header: no phone, no photo, no birth date (international norm; the PDF is public)
\begin{{center}}
  {{\LARGE\textbf{{{tex(s["name"])}}}}}\\[4pt]
  \small
  \newcommand{{\ico}}[1]{{{{\color{{muted}}#1}}~}}%
  \ico{{\faMapMarker*}}{tex(s["place"])}, France \qquad
  \href{{mailto:{s["email"]}}}{{\ico{{\faEnvelope}}{s["email"]}}} \qquad
  \href{{{s["url"].rstrip("/")}}}{{\ico{{\faGlobe}}{host}}} \qquad
  \href{{{s["github"]}}}{{\ico{{\faGithub}}{gh}}} \qquad
  \href{{{s["linkedin"]}}}{{\ico{{\faLinkedin}}{li}}}
\end{{center}}

\textbf{{Research interests:}} {r"~\textperiodcentered{} ".join(tex(x) for x in DATA["person"]["drawn_to"])}.
"""


def section(title):
    return f"\n% {'-' * 78}\n\\section*{{{title}}}\n"


def education():
    out = [section("Education")]
    for e in DATA["education"]:
        out.append(f"\n\\entry{{{tex(e['school'])}}}{{{tex(e['city'])}}}{{{tex(e['degree'])}}}{{{dates(e['dates'])}}}\n"
                   f"\\coursework{{{tex(e['coursework'])}}}\n")
    return "".join(out)


def research():
    items = [e for e in DATA["experience"] if e.get("cv_org")]
    out = [section("Research Experience")]
    for k, e in enumerate(items):
        out.append(f"\n\\entry{{{tex(e['cv_org'])}}}{{{tex(e['city'])}}}%\n{{{tex(e['cv_role'])}}}{{{span(e)}}}\n"
                   f"{tex(e['cv_text'])}\n")
        if e.get("cv_bullets"):
            out.append("\\begin{itemize}\n" + "".join(f"  \\item {tex(b)}\n" for b in e["cv_bullets"]) + "\\end{itemize}\n")
        if k < len(items) - 1:
            out.append("\\vspace{3pt}\n")
    return "".join(out)


def projects():
    items = [e for e in DATA["work"] if e.get("cv_title")]
    if not items:
        return ""
    out = [section("Research Projects")]
    for k, e in enumerate(items):
        out.append(f"\n\\entry{{{tex(e['cv_title'])}}}{{{tex(e['city'])}}}%\n{{{tex(e['cv_role'])}}}{{{span(e)}}}\n"
                   f"{tex(e['cv_text'])}\n")
        if k < len(items) - 1:
            out.append("\\vspace{3pt}\n")
    return "".join(out)


def listed(key, title):
    """Publications (those marked cv = true), talks, teaching: a section once there is an entry."""
    items = [e for e in DATA.get(key, []) if key != "publications" or e.get("cv")]
    if not items:
        return ""
    lines = []
    for e in items:
        what = tex(e.get("title", ""))
        where = tex(e.get("venue", "") or e.get("authors", ""))
        lines.append(f"  \\item {what}{', ' + where if where else ''}{' (' + e['date'] + ')' if e.get('date') else ''}\n")
    return section(title) + "\\begin{itemize}\n" + "".join(lines) + "\\end{itemize}\n"


def skills():
    langs = ", ".join(f"{n} ({lvl})" for n, lvl in DATA["person"]["languages"])
    rows = [*DATA["cv"]["skills"], ["Languages", langs]]
    return section("Skills") + "\n" + "".join(f"\\skill{{{tex(a)}}}{{{tex(b)}}}\n" for a, b in rows)


def document():
    pre = PREAMBLE.replace("@NAME@", tex(DATA["site"]["name"])).replace("@KEYWORDS@", tex(DATA["cv"]["keywords"]))
    body = (header() + education() + research() + projects() + listed("publications", "Publications")
            + listed("talks", "Talks and Posters") + listed("teaching", "Teaching") + skills())
    return pre + body + "\n\\end{document}\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", action="store_true", help="only write _cv/cv.tex")
    a = ap.parse_args()
    OUT.mkdir(exist_ok=True)
    (OUT / "cv.tex").write_text(document())
    print("  _cv/cv.tex")
    if a.tex:
        return
    r = subprocess.run(["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", "cv.tex"],
                       cwd=OUT, capture_output=True, text=True)
    if r.returncode:
        sys.exit(r.stdout[-3000:])
    pages = subprocess.run(["pdfinfo", str(OUT / "cv.pdf")], capture_output=True, text=True).stdout
    n = int(re.search(r"Pages:\s+(\d+)", pages).group(1))
    shutil.copyfile(OUT / "cv.pdf", PDF)
    print(f"  {PDF.relative_to(ROOT)} ({n} page{'s' if n > 1 else ''})")
    if n > 1:
        print("  warning: the CV runs over one page")


if __name__ == "__main__":
    main()
